### ISSUE TITLE
CS Study - 211202, 211209 목요일 19시까지(수정)

### ISSUE THREAD

**Issue by okstring** [iOS-study-delicato/CS-Study#8]
모여서 정한대로 범위, 스터디 방식이 변경됐습니다.
본인에게 가장 도움이 될 만한 챕터를 하나 선택해 발표를 준비해주세요

기한은 11/28 일요일에서 월요일로 넘어가는 00시 입니다 💪

`3장 메모리와 디스크의 핵심: 순차논리`
`4장 컴퓨터 내부 구조`
`5장 컴퓨터 아키테거와 운영체제`
`6장 입출력과 네트워킹`
`7장 데이터 구조와 처리`
`9장 웹 브라우저`
`10장 애플리케이션 프로그래밍과 시스템 프로그래밍`
`11장 성능 향상을 위한 알고리즘 기법`
`14장 세상을 바꾸는 기계 지능`
`15장 훌륭한 프로구래머가 되기 위한 팁과 경험담`

**Comment by 1song2** [comment]
7장 하고 싶습니다 :)

**Comment by okstring** [comment]
15장 준비해오겠습니다!

**Comment by HongzCloud** [comment]
6장 입출력과 네트워킹 하겠습니다.

**Comment by JUNGYUN-Daegu** [comment]
저는 5장 컴퓨터 아키텍쳐와 운영체제 해오겠습니다. 늦어서 죄송합니다 ㅠㅜ

**Comment by okstring** [comment]
다음주 챕터 선정 comment는 여기에 이어서 부탁드립니다~!

**Comment by 1song2** [comment]
**9장 웹 브라우저** 준비해오겠습니다!

**Comment by okstring** [comment]
14장 세상을 바꾸는 기계 지능을 준비해오겠습니다 :)

**Comment by JUNGYUN-Daegu** [comment]
저는 5장 나머지 부분 이어서 하겠습니다~!
